### ISSUE TITLE
Cmake errors

### ISSUE THREAD

**Issue by msempere** [sharpyfox/cassandra_libs_installer#1]
rtbkit@ip-10-106-137-8:~/workspace/cassandra_libs_installer$ make
Scanning dependencies of target cassandra
[ 12%] Building CXX object CMakeFiles/cassandra.dir/src/Cassandra.cpp.o
[ 25%] Building CXX object CMakeFiles/cassandra.dir/src/Cassandra_server.skeleton.cpp.o
[ 37%] Building CXX object CMakeFiles/cassandra.dir/src/cassandra_constants.cpp.o
In file included from /home/rtbkit/workspace/cassandra_libs_installer/src/cassandra_constants.cpp:7:0:
/home/rtbkit/workspace/cassandra_libs_installer/include/cassandra_constants.h:18:15: error: expected unqualified-id before string constant
/home/rtbkit/workspace/cassandra_libs_installer/src/cassandra_constants.cpp: In constructor ‘org::apache::cassandra::cassandraConstants::cassandraConstants()’:
/home/rtbkit/workspace/cassandra_libs_installer/src/cassandra_constants.cpp:14:13: error: assignment of read-only location ‘"1.0.0-dev"’
/home/rtbkit/workspace/cassandra_libs_installer/src/cassandra_constants.cpp:14:13: error: incompatible types in assignment of ‘const char [8]’ to ‘const char [10]’
make[2]: **\* [CMakeFiles/cassandra.dir/src/cassandra_constants.cpp.o] Error 1
make[1]: **\* [CMakeFiles/cassandra.dir/all] Error 2
make: **\* [all] Error 2

**Comment by sharpyfox** [comment]
@msempere thanks for your report. Please specify your OS and compiler version
